### ISSUE TITLE
ClamAV 0.103.2

### ISSUE THREAD

**Issue by RvdHout** [clamwin/clamav-win32#10]
Hi Gianluigi,

ClamAV 0.103.2 is out quite a while now, are you planning to upgrade your Native Win Port?

**Comment by m33m33** [comment]
If you have no time right now to make a new build, would you share a cookbook to produce a build from this repository, using mingw32 to build a 32 bit executable ?

Something like:
- Get sources
`git clone https://github.com/clamwin/clamav-win32.git`
- Get Mingw32
`wget https://github.com/jmeubank/tdm-gcc/releases/download/v9.2.0-tdm-1/tdm-gcc-9.2.0.exe`
- Get Cmake
`wget https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2-windows-i386.zip`
- unpack mingw32 and cmake in the same directory "mingw32" to ease with path and env variables
-load mingw environment variables
`\mingw32\bin\mingwvars.bat`
- test gcc and cmake
`gcc -v`      should show the version
`cmake --version`      should show the version
- Get libraries and dependices
`wget openssl` etc ? (I don't know yet)
- run cmake to generate mingw makefiles, in the clamav-w32 source directory
`cmake -G "MinGW Makefiles" .`
...

here I am stuck because of missing dependices

**Comment by sherpya** [comment]
I build mingw version on linux, it's rather simple if you have a working mingw cross compiler, perhaps you will still build my latest version and not new one without rebasing e merging upstream

you need to clone --recursive, then mkdir build, cd into build and call
`cmake -DCMAKE_TOOLCHAIN_FILE=$(pwd)/../cmake/toolchain-mingw-x86.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/tmp/clamav" ..`

then make

**Comment by m33m33** [comment]
Great, many thanks :)

On ubuntu it just need ``gcc-mingw-w64-i686 g++-mingw-w64-i686 cmake check`` and your latest update started building here

**Comment by RvdHout** [comment]
thx for the update!
